owner: eyenx # Your GitHub username
repo: upptime # Your GitHub repository name

sites:
  - name: Blog
    url: https://eyenx.ch
  - name: pub.eyenx.ch
    url: https://pub.eyenx.ch
  - name: NextCloud
    url: $SITE_NEXTCLOUD
  - name: Git
    url: $SITE_GIT
  - name: Private CI
    url: $SITE_CI
  - name: Mail
    url: $SITE_MAIL
  - name: Container Registry
    url: $SITE_CR
  - name: Matrix
    url: $SITE_MATRIX
  - name: Whoogle
    url: $SITE_WHOOGLE
  - name: AUR Repo
    url: https://aur.eyenx.ch/x86_64/eyenx.db.tar.gz
  - name: Wallabag
    url: $SITE_WB
  - name: upptime
    url: https://upptime.eyenx.ch

status-website:
  cname: upptime.eyenx.ch
  name: service status
  logoUrl: https://avatars.githubusercontent.com/u/1947882?s=460&u=1754c8d2ff687c003d18f279f93217688d805346
  introTitle: "Welcome to my service status page which uses **real-time** data from [GitHub](https://github.com/eyenx/upptime)."

    #commitMessages:
  #  commitAuthorName: "eyenx's upptime"
    #  commitAuthorEmail: "eye@eyenx.ch"
