owner: eyenx # Your GitHub username
repo: upptime # Your GitHub repository name

sites:
  - name: Blog
    url: https://eyenx.ch
  - name: pub.eyenx.ch
    url: https://pub.eyenx.ch
  - name: NextCloud
    url: $SITE_NEXTCLOUD
  - name: Git
    url: $SITE_GIT
  - name: Private CI
    url: $SITE_CI
  - name: Mail
    url: $SITE_MAIL
  - name: Container Registry
    url: $SITE_CR
  - name: Matrix
    url: $SITE_MATRIX
  - name: Whoogle
    url: $SITE_WHOOGLE
  - name: AUR Repo
    url: https://aur.eyenx.ch
  - name: Wallabag
    url: $SITE_WB
  - name: upptime
    url: https://upptime.eyenx.ch

status-website:
  cname: upptime.eyenx.ch
  logoUrl: https://avatars.githubusercontent.com/u/1947882?s=460&u=1754c8d2ff687c003d18f279f93217688d805346&v=4
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is [eyenx's](https://github.com/eyenx/upptime) status page which uses **real-time** data from GitHub.


commitMessages:
  commitAuthorName: "eyenx's upptime"
  commitAuthorEmail: "upptime@eyenx.ch"
